[selection]
  save_to_clipboard = true

[cursor]
  [cursor.style]
  blinking = "Always"

[terminal.shell]
#program = "C:\\Windows\\System32\\wsl.exe"
#args = ["--cd /mnt/c/Users/chryssoc -d Ubuntu"]
program = "C:\\Windows\\System32\\wsl.exe"
#args = ["--cd /mnt/c/Users/chryssoc -d Ubuntu-18.04"]
#args = ["--cd /mnt/c/Users/chryssoc -d Ubuntu"]
args = ["-d Ubuntu"]

# [font]
# size = 12.0
#
# [font.bold]
# family = "Consolas"
# style = "Bold"
#
#   [font.bold_italic]
#   family = "Consolas"
#   style = "Bold Italic"
#
#   [font.italic]
#   family = "Consolas"
#   style = "Italic"
#
#   [font.normal]
#   family = "Consolas"
#   style = "Regular"

# [font.bold]
# family = "Cascadia Mono"
# style = "Bold"
#
#   [font.bold_italic]
#   family = "Cascadia Mono"
#   style = "Bold Italic"
#
#   [font.italic]
#   family = "Cascadia Mono"
#   style = "Italic"
#
#   [font.normal]
#   family = "Cascadia Mono"

[font]
  #normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
  #bold = { family = "FiraCode Nerd Font Moni", style = "Bold" }
  #italic = { family = "FiraCode Nerd Font Moni", style = "Italic" }
  #bold_italic = { family = "FiraCode Nerd Font Mono", style = "Bold Italic" }

  #normal = { family = "MesloLGS Nerd Font", style = "Regular" }
  #bold = { family = "MesloLGS Nerd Font", style = "Bold" }
  #italic = { family = "MesloLGS Nerd Font", style = "Italic" }
  #bold_italic = { family = "MesloLGS Nerd Font", style = "Bold Italic" }

  normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
  bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
  italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
  bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

  size = 12.0  # You can adjust the size as needed

[window]
  [window.dimensions]
  columns = 150
  lines = 40

# This keybinding seems to fix C-space in some situations
[[keyboard.bindings]]
key = "Space"
mods = "Control"
chars = "\u0000"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"

# ~/.config/alacritty/alacritty.toml

# Disable Alacrittyâ€™s own mouse bindings so that mouse events are forwarded
# to applications (like Emacs) running inside the terminal.


#[mouse]
#        bindings = []


#[terminal]
[env]
TERM = "xterm-256color"

[colors.primary]
foreground = "#FFFFFF"  # This sets the font color (white in this case)
background = "#000000"  # This sets the background color

